# Generated by Django 5.0.1 on 2026-09-01 18:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("barcode", models.CharField(max_length=50, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Medicine", "Medicine"),
                            ("Medical Supply", "Medical Supply"),
                        ],
                        default="Medicine",
                        max_length=100,
                    ),
                ),
                ("kind", models.CharField(default="Tablet", max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("OTC", "OTC"), ("RX", "Prescription")],
                        default="OTC",
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reorder_level", models.IntegerField(default=10)),
                ("shelf", models.CharField(max_length=50)),
                ("image_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "payment_terms",
                    models.CharField(blank=True, default="Net 30", max_length=50),
                ),
                ("lead_days", models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=100)),
                ("expiry", models.DateField()),
                ("quantity", models.IntegerField(default=0)),
                ("supplier_name", models.CharField(blank=True, max_length=200)),
                ("shelf", models.CharField(blank=True, max_length=50)),
                ("received_date", models.DateField(default=datetime.date.today)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("expiring-warning", "Expiring <60d"),
                            ("expiring-soon", "Expiring <30d"),
                            ("expired", "Expired"),
                            ("disposed", "Disposed"),
                        ],
                        default="good",
                        max_length=30,
                    ),
                ),
                ("disposed_qty", models.IntegerField(blank=True, null=True)),
                ("disposed_date", models.DateField(blank=True, null=True)),
                ("disposed_by", models.CharField(blank=True, max_length=200)),
                ("disposal_reason", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="pharmacy.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "cash_given",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("method", models.CharField(default="cash", max_length=20)),
                (
                    "cashier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("qty", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pharmacy.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pharmacy.salerecord",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="pharmacy.supplier",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("pharmacist", "Pharmacist"),
                            ("staff", "Counter Staff"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
